config/routes.rb
Rails.application.routes.draw do
  resources :food_business_permits
  resources :representators
  resources :offices
  resources :business_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/representator.rb
# == Schema Information
#
# Table name: representators
#
#  id         :bigint           not null, primary key
#  name       :string(255)      not null
#  address    :string(255)      not null
#  tel        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Representator < ApplicationRecord
end

app/controllers/representators_controller.rb
class RepresentatorsController < ApplicationController
  before_action :set_representator, only: [:show, :edit, :update, :destroy]

  # GET /representators
  # GET /representators.json
  def index
    @representators = Representator.all
  end

  # GET /representators/1
  # GET /representators/1.json
  def show
  end

  # GET /representators/new
  def new
    @representator = Representator.new
  end

  # GET /representators/1/edit
  def edit
  end

  # POST /representators
  # POST /representators.json
  def create
    @representator = Representator.new(representator_params)

    respond_to do |format|
      if @representator.save
        format.html { redirect_to @representator, notice: 'Representator was successfully created.' }
        format.json { render :show, status: :created, location: @representator }
      else
        format.html { render :new }
        format.json { render json: @representator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representators/1
  # PATCH/PUT /representators/1.json
  def update
    respond_to do |format|
      if @representator.update(representator_params)
        format.html { redirect_to @representator, notice: 'Representator was successfully updated.' }
        format.json { render :show, status: :ok, location: @representator }
      else
        format.html { render :edit }
        format.json { render json: @representator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representators/1
  # DELETE /representators/1.json
  def destroy
    @representator.destroy
    respond_to do |format|
      format.html { redirect_to representators_url, notice: 'Representator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_representator
      @representator = Representator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def representator_params
      params.require(:representator).permit(:name, :address, :tel)
    end
end

app/helpers/representators_helper.rb
module RepresentatorsHelper
end

app/views/representators/_form.html.erb
<%= form_with(model: representator, local: true) do |form| %>
  <% if representator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(representator.errors.count, "error") %> prohibited this representator from being saved:</h2>

      <ul>
      <% representator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/representators/edit.html.erb
<h1>Editing Representator</h1>

<%= render 'form', representator: @representator %>

<%= link_to 'Show', @representator %> |
<%= link_to 'Back', representators_path %>

app/views/representators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Representators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Tel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @representators.each do |representator| %>
      <tr>
        <td><%= representator.name %></td>
        <td><%= representator.address %></td>
        <td><%= representator.tel %></td>
        <td><%= link_to 'Show', representator %></td>
        <td><%= link_to 'Edit', edit_representator_path(representator) %></td>
        <td><%= link_to 'Destroy', representator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Representator', new_representator_path %>

app/views/representators/new.html.erb
<h1>New Representator</h1>

<%= render 'form', representator: @representator %>

<%= link_to 'Back', representators_path %>

app/views/representators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @representator.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @representator.address %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @representator.tel %>
</p>

<%= link_to 'Edit', edit_representator_path(@representator) %> |
<%= link_to 'Back', representators_path %>