config/routes.rb
Rails.application.routes.draw do
  resources :food_business_permits
  resources :representators
  resources :offices
  resources :business_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/business_types_controller.rb
class BusinessTypesController < ApplicationController
  before_action :set_business_type, only: [:show, :edit, :update, :destroy]

  # GET /business_types
  # GET /business_types.json
  def index
    @business_types = BusinessType.all
  end

  # GET /business_types/1
  # GET /business_types/1.json
  def show
  end

  # GET /business_types/new
  def new
    @business_type = BusinessType.new
  end

  # GET /business_types/1/edit
  def edit
  end

  # POST /business_types
  # POST /business_types.json
  def create
    @business_type = BusinessType.new(business_type_params)

    respond_to do |format|
      if @business_type.save
        format.html { redirect_to @business_type, notice: 'Business type was successfully created.' }
        format.json { render :show, status: :created, location: @business_type }
      else
        format.html { render :new }
        format.json { render json: @business_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_types/1
  # PATCH/PUT /business_types/1.json
  def update
    respond_to do |format|
      if @business_type.update(business_type_params)
        format.html { redirect_to @business_type, notice: 'Business type was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_type }
      else
        format.html { render :edit }
        format.json { render json: @business_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_types/1
  # DELETE /business_types/1.json
  def destroy
    @business_type.destroy
    respond_to do |format|
      format.html { redirect_to business_types_url, notice: 'Business type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_type
      @business_type = BusinessType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_type_params
      params.require(:business_type).permit(:name)
    end
end

app/helpers/business_types_helper.rb
module BusinessTypesHelper
end

app/views/business_types/_form.html.erb
<%= form_with(model: business_type, local: true) do |form| %>
  <% if business_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business_type.errors.count, "error") %> prohibited this business_type from being saved:</h2>

      <ul>
      <% business_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/business_types/edit.html.erb
<h1>Editing Business Type</h1>

<%= render 'form', business_type: @business_type %>

<%= link_to 'Show', @business_type %> |
<%= link_to 'Back', business_types_path %>

app/views/business_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Business Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_types.each do |business_type| %>
      <tr>
        <td><%= business_type.name %></td>
        <td><%= link_to 'Show', business_type %></td>
        <td><%= link_to 'Edit', edit_business_type_path(business_type) %></td>
        <td><%= link_to 'Destroy', business_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business Type', new_business_type_path %>

app/views/business_types/new.html.erb
<h1>New Business Type</h1>

<%= render 'form', business_type: @business_type %>

<%= link_to 'Back', business_types_path %>

app/views/business_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @business_type.name %>
</p>

<%= link_to 'Edit', edit_business_type_path(@business_type) %> |
<%= link_to 'Back', business_types_path %>