config/routes.rb
Rails.application.routes.draw do
  resources :food_business_permits
  resources :representators
  resources :offices
  resources :business_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/food_business_permit.rb
# == Schema Information
#
# Table name: food_business_permits
#
#  id               :bigint           not null, primary key
#  office_id        :bigint
#  representator_id :bigint
#  business_type_id :bigint
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class FoodBusinessPermit < ApplicationRecord
  require 'csv'
  belongs_to :office
  belongs_to :representator
  belongs_to :business_type

  class << self
    def insert_seed_data
      file = File.join(Rails.root, "seed_data.csv")
      CSV.foreach(file, headers: true) do |row|
        next if row[1].blank?
        office = Office.find_or_create_by(name: row[1], address1: row[2], address2: row[3])
        type = BusinessType.find_or_create_by(name: row[6])
        if row[4].present?
          rep = Representator.find_or_create_by(name: row[4], address: row[5], tel: row[8])
          FoodBusinessPermit.create!(office_id: office.id, business_type_id: type.id, representator_id: rep.id)
        end
      end
    end
  end
end

app/controllers/food_business_permits_controller.rb
class FoodBusinessPermitsController < ApplicationController
  before_action :set_food_business_permit, only: [:show, :edit, :update, :destroy]

  # GET /food_business_permits
  # GET /food_business_permits.json
  def index
    @food_business_permits = FoodBusinessPermit.all
  end

  # GET /food_business_permits/1
  # GET /food_business_permits/1.json
  def show
  end

  # GET /food_business_permits/new
  def new
    @food_business_permit = FoodBusinessPermit.new
  end

  # GET /food_business_permits/1/edit
  def edit
  end

  # POST /food_business_permits
  # POST /food_business_permits.json
  def create
    @food_business_permit = FoodBusinessPermit.new(food_business_permit_params)

    respond_to do |format|
      if @food_business_permit.save
        format.html { redirect_to @food_business_permit, notice: 'Food business permit was successfully created.' }
        format.json { render :show, status: :created, location: @food_business_permit }
      else
        format.html { render :new }
        format.json { render json: @food_business_permit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_business_permits/1
  # PATCH/PUT /food_business_permits/1.json
  def update
    respond_to do |format|
      if @food_business_permit.update(food_business_permit_params)
        format.html { redirect_to @food_business_permit, notice: 'Food business permit was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_business_permit }
      else
        format.html { render :edit }
        format.json { render json: @food_business_permit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_business_permits/1
  # DELETE /food_business_permits/1.json
  def destroy
    @food_business_permit.destroy
    respond_to do |format|
      format.html { redirect_to food_business_permits_url, notice: 'Food business permit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_business_permit
      @food_business_permit = FoodBusinessPermit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_business_permit_params
      params.require(:food_business_permit).permit(:office_id, :representator_id, :business_type_id)
    end
end

app/helpers/food_business_permits_helper.rb
module FoodBusinessPermitsHelper
end

app/views/food_business_permits/_form.html.erb
<%= form_with(model: food_business_permit, local: true) do |form| %>
  <% if food_business_permit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_business_permit.errors.count, "error") %> prohibited this food_business_permit from being saved:</h2>

      <ul>
      <% food_business_permit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :office_id %>
    <%= form.text_field :office_id %>
  </div>

  <div class="field">
    <%= form.label :representator_id %>
    <%= form.text_field :representator_id %>
  </div>

  <div class="field">
    <%= form.label :business_type_id %>
    <%= form.text_field :business_type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_business_permits/edit.html.erb
<h1>Editing Food Business Permit</h1>

<%= render 'form', food_business_permit: @food_business_permit %>

<%= link_to 'Show', @food_business_permit %> |
<%= link_to 'Back', food_business_permits_path %>

app/views/food_business_permits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Business Permits</h1>

<table>
  <thead>
    <tr>
      <th>Office</th>
      <th>Representator</th>
      <th>Business type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_business_permits.each do |food_business_permit| %>
      <tr>
        <td><%= food_business_permit.office %></td>
        <td><%= food_business_permit.representator %></td>
        <td><%= food_business_permit.business_type %></td>
        <td><%= link_to 'Show', food_business_permit %></td>
        <td><%= link_to 'Edit', edit_food_business_permit_path(food_business_permit) %></td>
        <td><%= link_to 'Destroy', food_business_permit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Business Permit', new_food_business_permit_path %>

app/views/food_business_permits/new.html.erb
<h1>New Food Business Permit</h1>

<%= render 'form', food_business_permit: @food_business_permit %>

<%= link_to 'Back', food_business_permits_path %>

app/views/food_business_permits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Office:</strong>
  <%= @food_business_permit.office %>
</p>

<p>
  <strong>Representator:</strong>
  <%= @food_business_permit.representator %>
</p>

<p>
  <strong>Business type:</strong>
  <%= @food_business_permit.business_type %>
</p>

<%= link_to 'Edit', edit_food_business_permit_path(@food_business_permit) %> |
<%= link_to 'Back', food_business_permits_path %>